# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('syg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='elev',
            name='klasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruppeapp.Klasse'),
        ),
    ]
