# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gruppeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=32)),
                ('antalgrupper', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GruppeElev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gruppeapp.Gruppe')),
            ],
        ),
    ]
