# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gruppeapp', '0003_gruppeelev_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
