# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gruppeapp', '0010_klasse_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elev',
            name='syg',
        ),
    ]
