# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-01 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruppeapp', '0011_remove_elev_syg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('ishorizontal', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
